Split unit test and integration test reporting

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -29,6 +29,14 @@ jobs:
       - name: Build
         run: ./g build --no-daemon
 
+      - name: Publish Test Report
+        uses: mikepenz/action-junit-report@v3
+        if: success() || failure() # always run even if the previous step fails
+        with:
+          report_paths: '**/build/test-results/unitTest/TEST-*.xml'
+          require_tests: false # TODO: enable this once there are unit tests
+          check_name: Unit Tests Report
+
       - name: Integration tests
         run: ./g integrationTest --no-daemon
 
@@ -36,5 +44,6 @@ jobs:
         uses: mikepenz/action-junit-report@v3
         if: success() || failure() # always run even if the previous step fails
         with:
-          report_paths: '**/build/test-results/**/TEST-*.xml'
+          report_paths: '**/build/test-results/integrationTest/TEST-*.xml'
           require_tests: true
+          check_name: Integration Tests Report
